import type { SampleDataset } from "@/types";

export const SAMPLE_DATASETS: Record<string, SampleDataset> = {
  product_reviews: {
    name: "Product Reviews",
    description: "20 product reviews with sentiment, category, and ratings",
    data: [
      { review_id: "REV0001", text: "I absolutely love this product! Best purchase ever. The quality exceeded my expectations.", category: "Electronics", rating: 5, date: "2024-01-15" },
      { review_id: "REV0002", text: "Terrible experience. Would not recommend to anyone. Broke after two days of use.", category: "Clothing", rating: 1, date: "2024-01-14" },
      { review_id: "REV0003", text: "It's okay, nothing special but does the job. Average quality for the price.", category: "Home", rating: 3, date: "2024-01-13" },
      { review_id: "REV0004", text: "Amazing quality and fast shipping. Very happy with my purchase!", category: "Electronics", rating: 5, date: "2024-01-12" },
      { review_id: "REV0005", text: "Broke after one week. Complete waste of money. Customer service was unhelpful.", category: "Toys", rating: 1, date: "2024-01-11" },
      { review_id: "REV0006", text: "Great value for money. Exactly as described and arrived quickly.", category: "Home", rating: 4, date: "2024-01-10" },
      { review_id: "REV0007", text: "Size runs small, but otherwise good quality material. Would buy again in larger size.", category: "Clothing", rating: 3, date: "2024-01-09" },
      { review_id: "REV0008", text: "Outstanding product! My kids love it and it's very durable.", category: "Toys", rating: 5, date: "2024-01-08" },
      { review_id: "REV0009", text: "Not as described. The color is completely different from the photos.", category: "Home", rating: 2, date: "2024-01-07" },
      { review_id: "REV0010", text: "Perfect gift! Came beautifully packaged and works flawlessly.", category: "Electronics", rating: 5, date: "2024-01-06" },
      { review_id: "REV0011", text: "Disappointing quality. Stitching came undone after first wash.", category: "Clothing", rating: 2, date: "2024-01-05" },
      { review_id: "REV0012", text: "Solid product. Does what it says. Nothing fancy but reliable.", category: "Electronics", rating: 4, date: "2024-01-04" },
      { review_id: "REV0013", text: "Way overpriced for what you get. Similar products cost half as much.", category: "Home", rating: 2, date: "2024-01-03" },
      { review_id: "REV0014", text: "Excellent build quality and very intuitive to use. Highly recommend!", category: "Electronics", rating: 5, date: "2024-01-02" },
      { review_id: "REV0015", text: "Arrived damaged. Packaging was inadequate for the item.", category: "Toys", rating: 1, date: "2024-01-01" },
      { review_id: "REV0016", text: "Good but not great. Expected better based on the price point.", category: "Clothing", rating: 3, date: "2023-12-31" },
      { review_id: "REV0017", text: "Perfect for what I needed. Fast delivery and well packaged.", category: "Home", rating: 4, date: "2023-12-30" },
      { review_id: "REV0018", text: "Absolutely fantastic! Exceeded all my expectations in every way.", category: "Electronics", rating: 5, date: "2023-12-29" },
      { review_id: "REV0019", text: "Horrible customer service. Took 3 weeks to arrive and was wrong item.", category: "Clothing", rating: 1, date: "2023-12-28" },
      { review_id: "REV0020", text: "Decent product. Gets the job done without any fuss.", category: "Toys", rating: 3, date: "2023-12-27" },
    ],
  },

  healthcare_interviews: {
    name: "Healthcare Worker Interviews",
    description: "15 interview responses from healthcare workers about their experiences",
    data: [
      { participant_id: "HCW001", role: "Nurse", experience_years: 5, response: "The pandemic changed everything. We went from a normal routine to crisis mode overnight. I've never felt so exhausted yet so purposeful in my career." },
      { participant_id: "HCW002", role: "Doctor", experience_years: 12, response: "Burnout is real and it's everywhere. I see colleagues leaving the profession weekly. The system needs fundamental change, not just appreciation posts." },
      { participant_id: "HCW003", role: "Nurse", experience_years: 3, response: "What keeps me going is the patients. When someone recovers and thanks you, it reminds you why you chose this path despite all the challenges." },
      { participant_id: "HCW004", role: "Paramedic", experience_years: 8, response: "We're chronically underpaid and overworked. I love what I do, but I can't pay my mortgage. Something has to give eventually." },
      { participant_id: "HCW005", role: "Doctor", experience_years: 20, response: "The administrative burden has become unbearable. I spend more time on paperwork than with patients. That's not why I went to medical school." },
      { participant_id: "HCW006", role: "Nurse", experience_years: 7, response: "Team support makes all the difference. When colleagues have your back, even the hardest shifts become manageable. We're each other's lifeline." },
      { participant_id: "HCW007", role: "Therapist", experience_years: 10, response: "Mental health resources for healthcare workers are sorely lacking. We treat everyone else but have no one to turn to when we're struggling." },
      { participant_id: "HCW008", role: "Paramedic", experience_years: 2, response: "I'm already questioning my career choice. The trauma exposure without proper support is taking a real toll on my mental health." },
      { participant_id: "HCW009", role: "Doctor", experience_years: 15, response: "Innovation in medicine is exciting, but the pace of change is overwhelming. Keeping up with new treatments while managing patient load is incredibly stressful." },
      { participant_id: "HCW010", role: "Nurse", experience_years: 25, response: "In my 25 years, I've seen it all. The dedication of my younger colleagues gives me hope, but the system keeps letting them down." },
      { participant_id: "HCW011", role: "Therapist", experience_years: 6, response: "Teletherapy has been transformative. It removed barriers for patients who couldn't access care before. The pandemic accelerated something positive." },
      { participant_id: "HCW012", role: "Nurse", experience_years: 4, response: "Patient ratios are dangerously high. It's impossible to provide quality care when you're responsible for too many patients simultaneously." },
      { participant_id: "HCW013", role: "Doctor", experience_years: 9, response: "The inequity in healthcare access is what troubles me most. I see patients who couldn't afford preventive care coming in with advanced conditions." },
      { participant_id: "HCW014", role: "Paramedic", experience_years: 14, response: "I've learned to compartmentalize, but it has a cost. Emotional numbness is a survival mechanism that damages personal relationships." },
      { participant_id: "HCW015", role: "Nurse", experience_years: 11, response: "Technology can help but it's not a solution to staffing problems. Apps don't replace human judgment and compassionate care." },
    ],
  },

  support_tickets: {
    name: "Customer Support Tickets",
    description: "10 customer support tickets with issue types and resolution status",
    data: [
      { ticket_id: "TKT001", subject: "Cannot login to account", description: "I've been trying to login for 3 days. Password reset doesn't work. Very frustrated.", priority: "High", status: "Open", created_at: "2024-01-15" },
      { ticket_id: "TKT002", subject: "Billing error on invoice", description: "I was charged twice for the same subscription. Please refund the duplicate charge immediately.", priority: "High", status: "Resolved", created_at: "2024-01-14" },
      { ticket_id: "TKT003", subject: "Feature request: dark mode", description: "Would love to see a dark mode option in the app. Many users have requested this.", priority: "Low", status: "Open", created_at: "2024-01-13" },
      { ticket_id: "TKT004", subject: "Data export not working", description: "The CSV export function produces corrupted files. This is blocking our monthly reporting.", priority: "Critical", status: "In Progress", created_at: "2024-01-12" },
      { ticket_id: "TKT005", subject: "Slow performance issues", description: "The application has been extremely slow for the past week. Pages take 30+ seconds to load.", priority: "High", status: "In Progress", created_at: "2024-01-11" },
      { ticket_id: "TKT006", subject: "Integration with Slack", description: "Is there a way to integrate notifications with our Slack workspace? Would be very useful.", priority: "Medium", status: "Open", created_at: "2024-01-10" },
      { ticket_id: "TKT007", subject: "Account deletion request", description: "Please delete my account and all associated data per GDPR requirements.", priority: "Medium", status: "Resolved", created_at: "2024-01-09" },
      { ticket_id: "TKT008", subject: "Mobile app crashes on startup", description: "App crashes immediately after opening on iOS 17. This started after the latest update.", priority: "Critical", status: "Open", created_at: "2024-01-08" },
      { ticket_id: "TKT009", subject: "Documentation unclear", description: "The API documentation for webhooks is confusing. Examples would be very helpful.", priority: "Low", status: "Open", created_at: "2024-01-07" },
      { ticket_id: "TKT010", subject: "Team member cannot access project", description: "I invited a team member but they cannot see the shared project. Please investigate.", priority: "High", status: "Resolved", created_at: "2024-01-06" },
    ],
  },

  learning_experience: {
    name: "Learning Experience Survey",
    description: "15 student responses about their online learning experiences",
    data: [
      { student_id: "STU001", program: "Computer Science", year: 2, response: "Online learning has given me flexibility I never had before. I can study at my own pace and revisit lectures. But I miss the spontaneous discussions in class." },
      { student_id: "STU002", program: "Business", year: 3, response: "The technical issues are constant. Poor internet, platform crashes, audio problems. It disrupts my concentration and wastes valuable time." },
      { student_id: "STU003", program: "Psychology", year: 1, response: "I feel isolated. College was supposed to be about making connections and building a network. Online learning robs you of that social experience." },
      { student_id: "STU004", program: "Engineering", year: 4, response: "For theoretical subjects it works fine. But lab work and hands-on projects simply cannot be replicated online. That's a significant gap in my education." },
      { student_id: "STU005", program: "Arts", year: 2, response: "Surprisingly, I've connected with more diverse perspectives online. Students from different countries share their views in ways that enrich my learning." },
      { student_id: "STU006", program: "Medicine", year: 3, response: "Clinical training can't be virtualized. I need real patients, real procedures. Online theory is fine but it's only half the education I need." },
      { student_id: "STU007", program: "Computer Science", year: 1, response: "The recorded lectures are amazing. I can pause, rewind, and watch at 1.5x speed. I've never been able to review material this effectively before." },
      { student_id: "STU008", program: "Business", year: 2, response: "Group projects are a nightmare online. Coordinating time zones, dealing with connectivity issues, and building team rapport virtually is incredibly challenging." },
      { student_id: "STU009", program: "Psychology", year: 4, response: "The professors who adapted their teaching methods to online have made it work well. Those who just transferred their lectures unchanged have failed their students." },
      { student_id: "STU010", program: "Engineering", year: 2, response: "Cost savings are real. No commute, no campus housing. This has made higher education accessible to me in a way traditional university couldn't." },
      { student_id: "STU011", program: "Arts", year: 3, response: "Feedback on creative work suffers online. The nuanced critique you get in person simply doesn't translate to video calls and text comments." },
      { student_id: "STU012", program: "Medicine", year: 2, response: "Mental health support has become more important than ever. The isolation combined with academic pressure is a dangerous combination." },
      { student_id: "STU013", program: "Computer Science", year: 3, response: "I've developed stronger self-discipline from online learning. No one is watching if you skip class. You have to be self-motivated, which is actually a valuable skill." },
      { student_id: "STU014", program: "Business", year: 1, response: "The library resources available online are incredible. I have access to more academic content than any physical library could provide." },
      { student_id: "STU015", program: "Psychology", year: 2, response: "Accessibility improvements have been remarkable. Students with disabilities have more tools and accommodations available in online formats." },
    ],
  },

  exit_interviews: {
    name: "Employee Exit Interviews",
    description: "10 employee exit interview responses",
    data: [
      { employee_id: "EMP001", department: "Engineering", tenure_years: 3, primary_reason: "Better opportunity", response: "I loved the team but the compensation hasn't kept pace with the market. I was offered 40% more elsewhere. It wasn't an easy decision." },
      { employee_id: "EMP002", department: "Sales", tenure_years: 1, primary_reason: "Management issues", response: "My manager's micromanagement style made it impossible to do my job effectively. I never felt trusted or empowered to make decisions." },
      { employee_id: "EMP003", department: "Marketing", tenure_years: 5, primary_reason: "Career growth", response: "After five years, I reached a ceiling here. There simply weren't opportunities to advance to the level I'm capable of reaching." },
      { employee_id: "EMP004", department: "HR", tenure_years: 2, primary_reason: "Work-life balance", response: "The always-on culture became unsustainable. I was expected to respond to messages at midnight and on weekends. My family life was suffering." },
      { employee_id: "EMP005", department: "Engineering", tenure_years: 4, primary_reason: "Company direction", response: "The strategic pivots every six months made it hard to build anything meaningful. I want to work somewhere with a clear, consistent vision." },
      { employee_id: "EMP006", department: "Design", tenure_years: 2, primary_reason: "Better opportunity", response: "The new role is fully remote and in a field I'm more passionate about. Nothing wrong with the company — it's just the right time for me to move on." },
      { employee_id: "EMP007", department: "Sales", tenure_years: 6, primary_reason: "Compensation", response: "Six years and only two raises. The lack of financial recognition for top performers sends a message about how the company values us." },
      { employee_id: "EMP008", department: "Engineering", tenure_years: 1, primary_reason: "Culture fit", response: "The actual culture didn't match what was described during hiring. I was promised innovation but found bureaucracy and resistance to new ideas." },
      { employee_id: "EMP009", department: "Customer Success", tenure_years: 3, primary_reason: "Management issues", response: "Constant reorganizations and changing reporting structures created chaos. We had four different managers in three years. It's exhausting." },
      { employee_id: "EMP010", department: "Marketing", tenure_years: 7, primary_reason: "Retirement", response: "After 7 wonderful years, it's time to retire. I'm proud of what we built together. This company gave me some of my best professional years." },
    ],
  },

  systematic_review: {
    name: "Systematic Review Abstracts",
    description: "20 mixed abstracts for abstract screener testing — RCTs, meta-analyses, animal studies, off-topic, non-English",
    data: [
      {
        title: "Randomised controlled trial of cognitive behavioural therapy for depression in adults: 12-month outcomes",
        abstract: "Background: Depression affects 280 million people worldwide. Objective: To evaluate the efficacy of cognitive behavioural therapy (CBT) compared to usual care in adults with major depressive disorder. Methods: A randomised controlled trial (RCT) was conducted with 240 adults (18–65 years) diagnosed with MDD. Participants were randomised 1:1 to 12 weeks of weekly CBT sessions or treatment as usual. Primary outcome was PHQ-9 score at 12 months. Results: CBT group showed significantly greater reduction in PHQ-9 scores (mean difference −4.2, 95% CI −5.8 to −2.6, p < 0.001). Remission rates were 48% vs 29%. Conclusions: CBT is an effective intervention for depression with durable effects at 12 months.",
        keywords: "cognitive behavioural therapy; depression; randomised controlled trial; mental health; PHQ-9",
        journal: "The Lancet Psychiatry",
        year: "2023",
        authors: "Watkins, E.R.; Taylor, R.S.; Byng, R.",
        doi: "10.1016/S2215-0366(23)00102-X",
      },
      {
        title: "Efficacy of mindfulness-based stress reduction on anxiety symptoms: a meta-analysis of 42 randomised trials",
        abstract: "Objective: To synthesise evidence on mindfulness-based stress reduction (MBSR) for anxiety disorders. Methods: We searched MEDLINE, PsycINFO, and Cochrane Central from inception to December 2022. Randomised controlled trials comparing MBSR to active or inactive controls in adults with anxiety disorders were included. Results: 42 RCTs (N = 3,847) met inclusion criteria. MBSR significantly reduced anxiety symptoms (SMD = −0.58, 95% CI −0.73 to −0.43). Effects were maintained at 6-month follow-up. Heterogeneity was moderate (I² = 54%). Conclusions: MBSR is effective for anxiety reduction across multiple anxiety disorder subtypes.",
        keywords: "mindfulness; MBSR; anxiety; meta-analysis; systematic review",
        journal: "Journal of Anxiety Disorders",
        year: "2023",
        authors: "Goldberg, S.B.; Tucker, R.P.; Greene, P.A.",
        doi: "10.1016/j.janxdis.2023.102614",
      },
      {
        title: "Effect of exercise on hippocampal volume in rodent models of depression",
        abstract: "Introduction: Animal models suggest exercise increases hippocampal neurogenesis. Methods: Forty male Sprague-Dawley rats were randomised to voluntary wheel running or sedentary conditions for 6 weeks following chronic mild stress induction. Hippocampal volume was assessed by MRI. BDNF levels were measured by ELISA. Results: Running rats showed 18% greater hippocampal volume and 2.3-fold higher BDNF expression compared to sedentary controls (all p < 0.01). Conclusions: Exercise promotes hippocampal plasticity in animal models of depression via BDNF-mediated neurogenesis.",
        keywords: "exercise; hippocampus; neurogenesis; BDNF; animal model; rat",
        journal: "Neuroscience",
        year: "2022",
        authors: "Chen, C.; Nakagawa, S.; An, Y.",
        doi: "10.1016/j.neuroscience.2022.07.018",
      },
      {
        title: "Pharmacokinetics of sertraline in elderly patients: a population modelling study",
        abstract: "Background: Age-related changes in hepatic metabolism alter drug pharmacokinetics. Objective: To characterise sertraline pharmacokinetics in adults aged ≥ 65 years. Methods: Population pharmacokinetic modelling was performed using data from 89 elderly patients. Clearance and volume of distribution were estimated using non-linear mixed-effects modelling. Results: Clearance was 35% lower in elderly patients compared to published adult values. Half-life extended to 38 hours. Dose adjustment guidance was derived from simulation. Conclusions: Sertraline doses may require reduction in elderly patients to avoid accumulation.",
        keywords: "sertraline; pharmacokinetics; elderly; dose adjustment; population modelling",
        journal: "Clinical Pharmacokinetics",
        year: "2021",
        authors: "Jornil, J.; Jensen, K.G.; Larsen, F.",
        doi: "10.1007/s40262-021-01014-8",
      },
      {
        title: "استخدام العلاج المعرفي السلوكي في معالجة الاكتئاب: مراجعة منهجية",
        abstract: "الهدف: مراجعة الدراسات العربية التي تناولت العلاج المعرفي السلوكي لعلاج الاكتئاب. الطريقة: تم مراجعة قواعد البيانات العربية والدولية للفترة 2010–2022. النتائج: 15 دراسة استوفت معايير الإدراج. تبين فاعلية العلاج المعرفي السلوكي في تخفيف أعراض الاكتئاب في السياق العربي بحجم تأثير متوسط إلى كبير. الاستنتاج: يوصى بتطبيق برامج CBT المكيفة ثقافياً مع ضرورة إجراء تجارب عشوائية محكومة.",
        keywords: "العلاج المعرفي السلوكي; الاكتئاب; مراجعة منهجية; الصحة النفسية",
        journal: "المجلة العربية للطب النفسي",
        year: "2022",
        authors: "الزهراني، م.; العمري، ر.",
        doi: "",
      },
      {
        title: "Machine learning prediction of antidepressant treatment response: systematic review and meta-analysis",
        abstract: "Background: Predicting antidepressant response remains challenging. Objective: To systematically review machine learning (ML) approaches for predicting antidepressant treatment response. Methods: Studies using ML to predict response or remission to antidepressant pharmacotherapy in adults with MDD were included. We searched PubMed, Embase, and IEEE Xplore. Results: 28 studies met inclusion criteria. Mean AUC was 0.76 (95% CI 0.71–0.81). EEG and neuroimaging features improved prediction over clinical variables alone. Conclusions: ML shows promise for personalised antidepressant selection but requires prospective validation.",
        keywords: "machine learning; antidepressant; prediction; MDD; pharmacotherapy",
        journal: "Translational Psychiatry",
        year: "2023",
        authors: "Perlis, R.H.; Iosifescu, D.V.; Castro, V.M.",
        doi: "10.1038/s41398-023-02409-6",
      },
      {
        title: "Cardiovascular safety of antidepressants in patients with comorbid heart disease: a UK Biobank cohort study",
        abstract: "Background: Antidepressants are frequently prescribed to cardiac patients despite limited safety data. Methods: A retrospective cohort study of 12,450 adults with both depression and established cardiovascular disease drawn from UK Biobank. Participants were followed for a median of 8.4 years. Primary outcome was major adverse cardiac events (MACE) at 5 years. Antidepressant classes compared: SSRIs, SNRIs, TCAs, and mirtazapine. Results: SSRIs were not associated with increased MACE risk (HR 0.97, 95% CI 0.88–1.07). TCAs were associated with a 23% increased risk of arrhythmia (HR 1.23, 95% CI 1.08–1.40). SNRIs showed borderline increased risk at high doses. Conclusions: SSRIs appear safe in cardiac patients; TCAs should be used with caution.",
        keywords: "antidepressants; cardiovascular disease; SSRI; TCA; cohort study; MACE; UK Biobank",
        journal: "European Heart Journal",
        year: "2022",
        authors: "Bhatt, D.L.; Steg, P.G.; Ohman, E.M.",
        doi: "10.1093/eurheartj/ehac312",
      },
      {
        title: "The impact of social media use on adolescent wellbeing: a 3-year longitudinal study",
        abstract: "Introduction: Social media use among adolescents has increased dramatically over the past decade. This longitudinal cohort study followed 3,200 adolescents aged 12–17 over three years across four US cities. Screen time and platform-specific usage (Instagram, TikTok, Snapchat) and wellbeing scores (SWLS, PHQ-A) were assessed at baseline, 12, 24, and 36 months. Results: Higher daily social media use (>3 hours) was associated with greater depressive symptoms at follow-up (β = 0.18, p < 0.001) particularly in girls aged 13–15. Passive scrolling predicted worse outcomes than active posting. Protective factors included parental monitoring and ≥60 minutes/day physical activity. Conclusions: Excessive passive social media use poses mental health risks for adolescent girls.",
        keywords: "social media; adolescents; depression; wellbeing; longitudinal; screen time",
        journal: "JAMA Pediatrics",
        year: "2023",
        authors: "Twenge, J.M.; Haidt, J.; Joiner, T.E.",
        doi: "10.1001/jamapediatrics.2023.0809",
      },
      {
        title: "Gut microbiome composition and major depressive disorder: a systematic review of human observational studies",
        abstract: "Background: The gut-brain axis has emerged as a promising target for mental health interventions. Objective: To systematically review human observational studies examining gut microbiome composition in individuals with clinical depression versus healthy controls. Methods: MEDLINE, EMBASE, and PsycINFO were searched to December 2022. Cross-sectional and longitudinal studies in adults with a clinical depression diagnosis confirmed by structured interview were included. Animal and in vitro studies were excluded. Results: 19 studies (N = 2,687) were included. Consistent reductions in Lactobacillus and Bifidobacterium genera were observed in depressed individuals. Elevated Bacteroides and Proteobacteria were reported in 12/19 studies. Findings were heterogeneous due to methodological variation. Conclusions: The gut microbiome may play a role in depression aetiology; RCT evidence for probiotic interventions is needed.",
        keywords: "gut microbiome; depression; gut-brain axis; Lactobacillus; Bifidobacterium; observational",
        journal: "Psychosomatic Medicine",
        year: "2023",
        authors: "Simpson, C.A.; Mu, A.; Haslam, N.",
        doi: "10.1097/PSY.0000000000001143",
      },
      {
        title: "Network meta-analysis of pharmacological treatments for acute bipolar depression",
        abstract: "Objective: To compare the efficacy and acceptability of all pharmacological treatments for acute bipolar depression using network meta-analysis. Methods: We searched major databases through June 2023 for RCTs of drug treatments versus placebo or each other in adults with bipolar depression (BP-I or BP-II). Primary outcomes were response rate, remission rate, and all-cause dropout. Treatments included mood stabilisers, atypical antipsychotics, and antidepressants. Results: 58 RCTs (N = 14,230) contributed to the network. Quetiapine (OR 2.61, 95% CrI 2.03–3.37), lurasidone (OR 2.26), and lithium (OR 1.89) had the highest probability of ranking among the most effective treatments. Lamotrigine showed the most favourable tolerability profile. Antidepressant monotherapy was not superior to placebo. Conclusions: Quetiapine and lurasidone have the strongest evidence base for acute bipolar depression.",
        keywords: "bipolar depression; network meta-analysis; pharmacotherapy; quetiapine; lurasidone; lithium",
        journal: "American Journal of Psychiatry",
        year: "2023",
        authors: "Cipriani, A.; Furukawa, T.A.; Salanti, G.",
        doi: "10.1176/appi.ajp.20220940",
      },
      {
        title: "Transcranial magnetic stimulation for treatment-resistant depression: a multicentre randomised sham-controlled trial",
        abstract: "Background: Treatment-resistant depression (TRD) affects up to 30% of patients with MDD. Repetitive transcranial magnetic stimulation (rTMS) is an established neuromodulation option, but its efficacy over sham in a large multicentre trial had not been established. Methods: 388 adults with TRD (failure of ≥2 adequate antidepressant trials) were randomised to active left dorsolateral prefrontal cortex rTMS (10 Hz, 3,000 pulses/session, 20 sessions) or sham. Primary outcome: response at 4 weeks (≥50% MADRS reduction). Results: Response rate 41.2% (active) vs 20.3% (sham), OR 2.76 (95% CI 1.74–4.38, p < 0.001). Remission 24.1% vs 10.8%. Effects sustained at 6-month follow-up. No serious adverse events. Conclusions: rTMS is effective and safe for TRD.",
        keywords: "transcranial magnetic stimulation; rTMS; treatment-resistant depression; neuromodulation; RCT",
        journal: "JAMA Psychiatry",
        year: "2023",
        authors: "Carpenter, L.L.; Janicak, P.G.; Aaronson, S.T.",
        doi: "10.1001/jamapsychiatry.2023.1093",
      },
      {
        title: "Prevalence of burnout among hospital physicians and nurses: a global meta-analysis 2015–2023",
        abstract: "Objective: To estimate the pooled prevalence of burnout among hospital-based physicians and nurses globally. Design: Systematic review and meta-analysis. Methods: PubMed, CINAHL, and PsycINFO were searched for cross-sectional studies reporting burnout prevalence using validated instruments (MBI, CBI, OLBI) from 2015 to 2023. Results: 142 studies (N = 228,000 clinicians) were included. Pooled burnout prevalence: 44.2% (95% CI 41.1–47.4%) among physicians and 38.7% (95% CI 35.9–41.6%) among nurses. Prevalence increased significantly post-COVID-19 pandemic (2020–2023 vs 2015–2019, OR 1.38). Emergency and ICU staff had highest rates. Conclusions: Burnout is highly prevalent in hospital staff and worsened during the pandemic, requiring systemic organisational interventions.",
        keywords: "burnout; physicians; nurses; meta-analysis; prevalence; healthcare workers",
        journal: "BMJ",
        year: "2023",
        authors: "Panagioti, M.; Geraghty, K.; Johnson, J.",
        doi: "10.1136/bmj-2022-072779",
      },
      {
        title: "Comparative efficacy of psychological therapies for post-traumatic stress disorder in adults: a network meta-analysis",
        abstract: "Background: Multiple psychological therapies for PTSD exist but their comparative efficacy is unclear. Methods: We conducted a network meta-analysis of RCTs. Adults with DSM-5 PTSD were eligible; pharmacological interventions were excluded. Primary outcome: PTSD symptom severity (PCL-5 or CAPS) post-treatment. Results: 96 RCTs (N = 8,904) were included. Trauma-focused CBT (TF-CBT, SMD −1.43), EMDR (SMD −1.28), and prolonged exposure (SMD −1.21) outperformed waitlist and active controls. TF-CBT and EMDR did not differ significantly from each other. Non-trauma-focused therapies (supportive counselling, relaxation) showed smaller effects. Dropout was highest in prolonged exposure (28%). Conclusions: Trauma-focused therapies should be first-line for PTSD.",
        keywords: "PTSD; CBT; EMDR; prolonged exposure; network meta-analysis; psychological therapy",
        journal: "Psychological Medicine",
        year: "2022",
        authors: "Bisson, J.I.; Roberts, N.P.; Andrew, M.",
        doi: "10.1017/S0033291722002690",
      },
      {
        title: "Childhood adverse experiences and adult onset depression: dose-response meta-analysis of 39 prospective cohort studies",
        abstract: "Background: Adverse childhood experiences (ACEs) are established risk factors for depression, but dose-response relationships have not been quantified. Objective: To synthesise prospective evidence on ACE burden and adult depression onset. Methods: 39 prospective cohort studies (N = 191,000; median follow-up 12 years) were included. Random-effects dose-response meta-analysis was performed. ACE types examined: physical/sexual/emotional abuse, neglect, parental mental illness, domestic violence, and household substance misuse. Results: Each additional ACE increased depression odds by 28% (OR 1.28 per ACE, 95% CI 1.22–1.34). Non-linear relationship observed: 4+ ACEs conferred OR 3.97 vs no ACEs. Population attributable fraction: 34% of adult depression cases attributable to ACEs. Conclusions: Prevention and early intervention targeting ACEs could substantially reduce depression burden.",
        keywords: "adverse childhood experiences; ACEs; depression; dose-response; prospective cohort",
        journal: "The Lancet",
        year: "2023",
        authors: "Hughes, K.; Bellis, M.A.; Hardcastle, K.A.",
        doi: "10.1016/S0140-6736(23)00741-9",
      },
      {
        title: "Effect of dietary omega-3 fatty acid supplementation on depressive symptoms: an updated meta-analysis",
        abstract: "Objective: To update the meta-analytic evidence on omega-3 polyunsaturated fatty acid (PUFA) supplementation for depressive symptoms. Methods: RCTs of omega-3 PUFA supplementation (fish oil, EPA, DHA) versus placebo in adults with depressive disorders or elevated depressive symptoms were included. Primary outcome: standardised mean difference in depression scale scores. Results: 35 trials (N = 6,982) were included. Omega-3 supplementation reduced depressive symptoms (SMD −0.39, 95% CI −0.52 to −0.26). EPA-dominant formulations (≥60% EPA) showed stronger effects (SMD −0.50) than DHA-dominant. Effects were consistent in MDD subgroup analysis. No significant publication bias detected. Conclusions: Omega-3 supplementation, particularly EPA-dominant formulations, has a modest but consistent antidepressant effect.",
        keywords: "omega-3; EPA; DHA; fish oil; depression; meta-analysis; supplementation",
        journal: "Translational Psychiatry",
        year: "2022",
        authors: "Mocking, R.J.T.; Harmsen, I.; Assies, J.",
        doi: "10.1038/s41398-022-01944-0",
      },
      {
        title: "Long-term safety and efficacy of lithium for bipolar disorder maintenance: a 20-year naturalistic cohort study",
        abstract: "Background: Lithium remains the gold standard for bipolar disorder maintenance despite limited long-term real-world data. Methods: A naturalistic cohort of 847 patients with bipolar I or II disorder who received lithium for ≥1 year was followed over a median of 11.3 years (range 1–20 years) in two specialist mood disorder clinics. Outcomes: relapse rates, hospitalisation, renal function trajectory, thyroid function, cognitive performance, and all-cause mortality. Results: Lithium maintained serum levels 0.6–0.8 mmol/L was associated with 62% reduction in relapse risk vs matched non-lithium period. Suicide rate: 0.28 per 100 patient-years (vs 1.6% general bipolar population). eGFR declined at 1.2 mL/min/year on average; 7.4% developed stage 3 CKD after 15+ years. Hypothyroidism occurred in 24.8%. Conclusions: Lithium is highly effective long-term with manageable but clinically important renal and thyroid risks requiring monitoring.",
        keywords: "lithium; bipolar disorder; maintenance; long-term safety; renal function; relapse prevention",
        journal: "Bipolar Disorders",
        year: "2023",
        authors: "Gitlin, M.J.; Frye, M.A.",
        doi: "10.1111/bdi.13302",
      },
      {
        title: "Interpersonal psychotherapy versus pharmacotherapy for postpartum depression: multicentre RCT",
        abstract: "Background: Postpartum depression (PPD) affects 10–15% of mothers. Many prefer non-pharmacological treatment given breastfeeding concerns. Methods: 312 women meeting DSM-5 criteria for MDD onset within 4 weeks of delivery were randomised to 12 weeks of interpersonal psychotherapy (IPT, weekly sessions), sertraline (50–150 mg/day), or combined treatment. Primary outcome: EPDS score at 12 weeks. All women were breastfeeding at enrolment. Results: IPT and sertraline were equally effective (EPDS reduction: −9.2 vs −9.5 points, p = 0.74). Combined treatment showed marginal superiority. Remission rates: IPT 54%, sertraline 57%, combined 68%. Infant exposure to sertraline via breastmilk was below detection threshold in 89% of infants. Conclusions: IPT is a safe and effective first-line option for breastfeeding mothers with PPD.",
        keywords: "postpartum depression; interpersonal psychotherapy; sertraline; breastfeeding; RCT; EPDS",
        journal: "BJOG",
        year: "2023",
        authors: "Sockol, L.E.; Epperson, C.N.; Barber, J.P.",
        doi: "10.1111/1471-0528.17463",
      },
      {
        title: "Influence of serotonin transporter gene polymorphisms on antidepressant response: a pharmacogenomics review",
        abstract: "The serotonin transporter gene (SLC6A4) has been extensively studied as a predictor of antidepressant response. The 5-HTTLPR polymorphism, consisting of short (S) and long (L) alleles, affects transcriptional efficiency and has been proposed to moderate SSRI response. We reviewed 62 pharmacogenomic studies examining this association. Overall findings were inconsistent: 31 reported significant effects, 27 did not, and 4 showed opposite-direction effects across different populations. Meta-analytic estimates ranged from no effect to modest association depending on ancestry and drug type. Challenges include small sample sizes, phenotypic heterogeneity, and population stratification. Conclusion: The clinical utility of SLC6A4 genotyping for antidepressant selection remains limited and is not currently recommended outside research settings.",
        keywords: "pharmacogenomics; serotonin transporter; 5-HTTLPR; SSRI; antidepressant response; SLC6A4",
        journal: "Pharmacogenomics Journal",
        year: "2021",
        authors: "Porcelli, S.; Fabbri, C.; Serretti, A.",
        doi: "10.1038/s41397-021-00218-8",
      },
      {
        title: "Depression in cancer patients: a systematic review of prevalence, screening tools, and treatment outcomes",
        abstract: "Background: Depression is the most common psychological comorbidity in cancer patients, adversely affecting quality of life and cancer outcomes. Objective: To review prevalence estimates, optimal screening instruments, and treatment efficacy evidence for depression in adult cancer populations. Methods: MEDLINE and PsycINFO were searched for systematic reviews, meta-analyses, and RCTs published 2010–2023. Results: Prevalence of clinical depression ranged from 8% to 24% depending on cancer type and assessment method. The PHQ-9 and HADS demonstrated acceptable sensitivity/specificity. Psychotherapy (CBT, acceptance and commitment therapy) produced significant symptom reduction (SMD −0.58 to −0.72). SSRIs were effective but evidence quality was moderate. Collaborative care models combining psychosocial and pharmacological treatment showed the strongest outcomes. Conclusions: Routine depression screening and stepped-care treatment should be integrated into oncology services.",
        keywords: "depression; cancer; oncology; prevalence; CBT; screening; collaborative care",
        journal: "Journal of Clinical Oncology",
        year: "2023",
        authors: "Fann, J.R.; Thomas-Rich, A.M.; Katon, W.J.",
        doi: "10.1200/JCO.22.02611",
      },
      {
        title: "Effect of acetylcholinesterase inhibitors on amyloid burden in APP/PS1 transgenic mice",
        abstract: "Introduction: Alzheimer's disease is characterised by amyloid-beta (Aβ) plaques and cholinergic deficits. Acetylcholinesterase inhibitors (AChEIs) improve cognitive symptoms but their effect on amyloid burden is unclear. Methods: APP/PS1 transgenic mice (n = 48) were treated with donepezil (5 mg/kg), rivastigmine (3 mg/kg), or vehicle for 12 weeks starting at 6 months of age. Amyloid burden was quantified by thioflavin-S staining and ELISA. Morris water maze assessed spatial learning. Results: Neither donepezil nor rivastigmine significantly reduced amyloid plaque count or Aβ42 levels compared to vehicle (all p > 0.05). Spatial learning improved significantly in treated mice (p = 0.003), dissociating cognitive and amyloid effects. Conclusions: AChEIs improve cognition without modifying amyloid pathology in this mouse model, consistent with their symptomatic mechanism.",
        keywords: "Alzheimer's disease; acetylcholinesterase inhibitors; amyloid; transgenic mice; donepezil; animal model",
        journal: "Neuropharmacology",
        year: "2022",
        authors: "Wang, L.; Bhatt, S.; Bhatt, D.",
        doi: "10.1016/j.neuropharm.2022.109083",
      },
    ],
  },

  mixed_feedback: {
    name: "Mixed Stakeholder Feedback",
    description: "10 stakeholder feedback responses from a mixed-methods study",
    data: [
      { respondent_id: "RSP001", stakeholder_type: "Community Member", region: "Urban", response: "The new policy has improved access to services dramatically. Wait times are down and staff are more helpful. Real positive change in our neighborhood." },
      { respondent_id: "RSP002", stakeholder_type: "Business Owner", region: "Rural", response: "Regulations are strangling small businesses. We can't compete with large corporations who can absorb compliance costs. It's driving us out of business." },
      { respondent_id: "RSP003", stakeholder_type: "NGO Representative", region: "Suburban", response: "Implementation was rushed without adequate community consultation. The underlying goals are right but the execution has created unnecessary friction." },
      { respondent_id: "RSP004", stakeholder_type: "Government Official", region: "Urban", response: "We've seen measurable improvements across all key performance indicators. The data clearly shows the program is working as intended." },
      { respondent_id: "RSP005", stakeholder_type: "Community Member", region: "Rural", response: "Nothing has changed for us in rural areas. All these improvements are happening in cities while we're left behind as always." },
      { respondent_id: "RSP006", stakeholder_type: "Academic Researcher", region: "Urban", response: "The evidence base for this intervention is mixed. Some outcomes show improvement while others show regression. More longitudinal data is needed." },
      { respondent_id: "RSP007", stakeholder_type: "Business Owner", region: "Urban", response: "The streamlined permitting process has saved us time and money. We were able to expand our operations because of these changes." },
      { respondent_id: "RSP008", stakeholder_type: "NGO Representative", region: "Rural", response: "Vulnerable populations are falling through the gaps. The system wasn't designed with their needs in mind and it shows in the outcomes data." },
      { respondent_id: "RSP009", stakeholder_type: "Community Member", region: "Suburban", response: "I appreciate the transparency in reporting. Knowing what's actually happening with public funds builds trust, even when results are mixed." },
      { respondent_id: "RSP010", stakeholder_type: "Academic Researcher", region: "Suburban", response: "This represents a significant policy innovation. The participatory design process was genuinely inclusive and the implementation reflects that." },
    ],
  },
};
