import type { SampleDataset } from "@/types";

export const SAMPLE_DATASETS: Record<string, SampleDataset> = {
  product_reviews: {
    name: "Product Reviews",
    description: "20 product reviews with sentiment, category, and ratings",
    data: [
      { review_id: "REV0001", text: "I absolutely love this product! Best purchase ever. The quality exceeded my expectations.", category: "Electronics", rating: 5, date: "2024-01-15" },
      { review_id: "REV0002", text: "Terrible experience. Would not recommend to anyone. Broke after two days of use.", category: "Clothing", rating: 1, date: "2024-01-14" },
      { review_id: "REV0003", text: "It's okay, nothing special but does the job. Average quality for the price.", category: "Home", rating: 3, date: "2024-01-13" },
      { review_id: "REV0004", text: "Amazing quality and fast shipping. Very happy with my purchase!", category: "Electronics", rating: 5, date: "2024-01-12" },
      { review_id: "REV0005", text: "Broke after one week. Complete waste of money. Customer service was unhelpful.", category: "Toys", rating: 1, date: "2024-01-11" },
      { review_id: "REV0006", text: "Great value for money. Exactly as described and arrived quickly.", category: "Home", rating: 4, date: "2024-01-10" },
      { review_id: "REV0007", text: "Size runs small, but otherwise good quality material. Would buy again in larger size.", category: "Clothing", rating: 3, date: "2024-01-09" },
      { review_id: "REV0008", text: "Outstanding product! My kids love it and it's very durable.", category: "Toys", rating: 5, date: "2024-01-08" },
      { review_id: "REV0009", text: "Not as described. The color is completely different from the photos.", category: "Home", rating: 2, date: "2024-01-07" },
      { review_id: "REV0010", text: "Perfect gift! Came beautifully packaged and works flawlessly.", category: "Electronics", rating: 5, date: "2024-01-06" },
      { review_id: "REV0011", text: "Disappointing quality. Stitching came undone after first wash.", category: "Clothing", rating: 2, date: "2024-01-05" },
      { review_id: "REV0012", text: "Solid product. Does what it says. Nothing fancy but reliable.", category: "Electronics", rating: 4, date: "2024-01-04" },
      { review_id: "REV0013", text: "Way overpriced for what you get. Similar products cost half as much.", category: "Home", rating: 2, date: "2024-01-03" },
      { review_id: "REV0014", text: "Excellent build quality and very intuitive to use. Highly recommend!", category: "Electronics", rating: 5, date: "2024-01-02" },
      { review_id: "REV0015", text: "Arrived damaged. Packaging was inadequate for the item.", category: "Toys", rating: 1, date: "2024-01-01" },
      { review_id: "REV0016", text: "Good but not great. Expected better based on the price point.", category: "Clothing", rating: 3, date: "2023-12-31" },
      { review_id: "REV0017", text: "Perfect for what I needed. Fast delivery and well packaged.", category: "Home", rating: 4, date: "2023-12-30" },
      { review_id: "REV0018", text: "Absolutely fantastic! Exceeded all my expectations in every way.", category: "Electronics", rating: 5, date: "2023-12-29" },
      { review_id: "REV0019", text: "Horrible customer service. Took 3 weeks to arrive and was wrong item.", category: "Clothing", rating: 1, date: "2023-12-28" },
      { review_id: "REV0020", text: "Decent product. Gets the job done without any fuss.", category: "Toys", rating: 3, date: "2023-12-27" },
    ],
  },

  healthcare_interviews: {
    name: "Healthcare Worker Interviews",
    description: "15 interview responses from healthcare workers about their experiences",
    data: [
      { participant_id: "HCW001", role: "Nurse", experience_years: 5, response: "The pandemic changed everything. We went from a normal routine to crisis mode overnight. I've never felt so exhausted yet so purposeful in my career." },
      { participant_id: "HCW002", role: "Doctor", experience_years: 12, response: "Burnout is real and it's everywhere. I see colleagues leaving the profession weekly. The system needs fundamental change, not just appreciation posts." },
      { participant_id: "HCW003", role: "Nurse", experience_years: 3, response: "What keeps me going is the patients. When someone recovers and thanks you, it reminds you why you chose this path despite all the challenges." },
      { participant_id: "HCW004", role: "Paramedic", experience_years: 8, response: "We're chronically underpaid and overworked. I love what I do, but I can't pay my mortgage. Something has to give eventually." },
      { participant_id: "HCW005", role: "Doctor", experience_years: 20, response: "The administrative burden has become unbearable. I spend more time on paperwork than with patients. That's not why I went to medical school." },
      { participant_id: "HCW006", role: "Nurse", experience_years: 7, response: "Team support makes all the difference. When colleagues have your back, even the hardest shifts become manageable. We're each other's lifeline." },
      { participant_id: "HCW007", role: "Therapist", experience_years: 10, response: "Mental health resources for healthcare workers are sorely lacking. We treat everyone else but have no one to turn to when we're struggling." },
      { participant_id: "HCW008", role: "Paramedic", experience_years: 2, response: "I'm already questioning my career choice. The trauma exposure without proper support is taking a real toll on my mental health." },
      { participant_id: "HCW009", role: "Doctor", experience_years: 15, response: "Innovation in medicine is exciting, but the pace of change is overwhelming. Keeping up with new treatments while managing patient load is incredibly stressful." },
      { participant_id: "HCW010", role: "Nurse", experience_years: 25, response: "In my 25 years, I've seen it all. The dedication of my younger colleagues gives me hope, but the system keeps letting them down." },
      { participant_id: "HCW011", role: "Therapist", experience_years: 6, response: "Teletherapy has been transformative. It removed barriers for patients who couldn't access care before. The pandemic accelerated something positive." },
      { participant_id: "HCW012", role: "Nurse", experience_years: 4, response: "Patient ratios are dangerously high. It's impossible to provide quality care when you're responsible for too many patients simultaneously." },
      { participant_id: "HCW013", role: "Doctor", experience_years: 9, response: "The inequity in healthcare access is what troubles me most. I see patients who couldn't afford preventive care coming in with advanced conditions." },
      { participant_id: "HCW014", role: "Paramedic", experience_years: 14, response: "I've learned to compartmentalize, but it has a cost. Emotional numbness is a survival mechanism that damages personal relationships." },
      { participant_id: "HCW015", role: "Nurse", experience_years: 11, response: "Technology can help but it's not a solution to staffing problems. Apps don't replace human judgment and compassionate care." },
    ],
  },

  support_tickets: {
    name: "Customer Support Tickets",
    description: "10 customer support tickets with issue types and resolution status",
    data: [
      { ticket_id: "TKT001", subject: "Cannot login to account", description: "I've been trying to login for 3 days. Password reset doesn't work. Very frustrated.", priority: "High", status: "Open", created_at: "2024-01-15" },
      { ticket_id: "TKT002", subject: "Billing error on invoice", description: "I was charged twice for the same subscription. Please refund the duplicate charge immediately.", priority: "High", status: "Resolved", created_at: "2024-01-14" },
      { ticket_id: "TKT003", subject: "Feature request: dark mode", description: "Would love to see a dark mode option in the app. Many users have requested this.", priority: "Low", status: "Open", created_at: "2024-01-13" },
      { ticket_id: "TKT004", subject: "Data export not working", description: "The CSV export function produces corrupted files. This is blocking our monthly reporting.", priority: "Critical", status: "In Progress", created_at: "2024-01-12" },
      { ticket_id: "TKT005", subject: "Slow performance issues", description: "The application has been extremely slow for the past week. Pages take 30+ seconds to load.", priority: "High", status: "In Progress", created_at: "2024-01-11" },
      { ticket_id: "TKT006", subject: "Integration with Slack", description: "Is there a way to integrate notifications with our Slack workspace? Would be very useful.", priority: "Medium", status: "Open", created_at: "2024-01-10" },
      { ticket_id: "TKT007", subject: "Account deletion request", description: "Please delete my account and all associated data per GDPR requirements.", priority: "Medium", status: "Resolved", created_at: "2024-01-09" },
      { ticket_id: "TKT008", subject: "Mobile app crashes on startup", description: "App crashes immediately after opening on iOS 17. This started after the latest update.", priority: "Critical", status: "Open", created_at: "2024-01-08" },
      { ticket_id: "TKT009", subject: "Documentation unclear", description: "The API documentation for webhooks is confusing. Examples would be very helpful.", priority: "Low", status: "Open", created_at: "2024-01-07" },
      { ticket_id: "TKT010", subject: "Team member cannot access project", description: "I invited a team member but they cannot see the shared project. Please investigate.", priority: "High", status: "Resolved", created_at: "2024-01-06" },
    ],
  },

  learning_experience: {
    name: "Learning Experience Survey",
    description: "15 student responses about their online learning experiences",
    data: [
      { student_id: "STU001", program: "Computer Science", year: 2, response: "Online learning has given me flexibility I never had before. I can study at my own pace and revisit lectures. But I miss the spontaneous discussions in class." },
      { student_id: "STU002", program: "Business", year: 3, response: "The technical issues are constant. Poor internet, platform crashes, audio problems. It disrupts my concentration and wastes valuable time." },
      { student_id: "STU003", program: "Psychology", year: 1, response: "I feel isolated. College was supposed to be about making connections and building a network. Online learning robs you of that social experience." },
      { student_id: "STU004", program: "Engineering", year: 4, response: "For theoretical subjects it works fine. But lab work and hands-on projects simply cannot be replicated online. That's a significant gap in my education." },
      { student_id: "STU005", program: "Arts", year: 2, response: "Surprisingly, I've connected with more diverse perspectives online. Students from different countries share their views in ways that enrich my learning." },
      { student_id: "STU006", program: "Medicine", year: 3, response: "Clinical training can't be virtualized. I need real patients, real procedures. Online theory is fine but it's only half the education I need." },
      { student_id: "STU007", program: "Computer Science", year: 1, response: "The recorded lectures are amazing. I can pause, rewind, and watch at 1.5x speed. I've never been able to review material this effectively before." },
      { student_id: "STU008", program: "Business", year: 2, response: "Group projects are a nightmare online. Coordinating time zones, dealing with connectivity issues, and building team rapport virtually is incredibly challenging." },
      { student_id: "STU009", program: "Psychology", year: 4, response: "The professors who adapted their teaching methods to online have made it work well. Those who just transferred their lectures unchanged have failed their students." },
      { student_id: "STU010", program: "Engineering", year: 2, response: "Cost savings are real. No commute, no campus housing. This has made higher education accessible to me in a way traditional university couldn't." },
      { student_id: "STU011", program: "Arts", year: 3, response: "Feedback on creative work suffers online. The nuanced critique you get in person simply doesn't translate to video calls and text comments." },
      { student_id: "STU012", program: "Medicine", year: 2, response: "Mental health support has become more important than ever. The isolation combined with academic pressure is a dangerous combination." },
      { student_id: "STU013", program: "Computer Science", year: 3, response: "I've developed stronger self-discipline from online learning. No one is watching if you skip class. You have to be self-motivated, which is actually a valuable skill." },
      { student_id: "STU014", program: "Business", year: 1, response: "The library resources available online are incredible. I have access to more academic content than any physical library could provide." },
      { student_id: "STU015", program: "Psychology", year: 2, response: "Accessibility improvements have been remarkable. Students with disabilities have more tools and accommodations available in online formats." },
    ],
  },

  exit_interviews: {
    name: "Employee Exit Interviews",
    description: "10 employee exit interview responses",
    data: [
      { employee_id: "EMP001", department: "Engineering", tenure_years: 3, primary_reason: "Better opportunity", response: "I loved the team but the compensation hasn't kept pace with the market. I was offered 40% more elsewhere. It wasn't an easy decision." },
      { employee_id: "EMP002", department: "Sales", tenure_years: 1, primary_reason: "Management issues", response: "My manager's micromanagement style made it impossible to do my job effectively. I never felt trusted or empowered to make decisions." },
      { employee_id: "EMP003", department: "Marketing", tenure_years: 5, primary_reason: "Career growth", response: "After five years, I reached a ceiling here. There simply weren't opportunities to advance to the level I'm capable of reaching." },
      { employee_id: "EMP004", department: "HR", tenure_years: 2, primary_reason: "Work-life balance", response: "The always-on culture became unsustainable. I was expected to respond to messages at midnight and on weekends. My family life was suffering." },
      { employee_id: "EMP005", department: "Engineering", tenure_years: 4, primary_reason: "Company direction", response: "The strategic pivots every six months made it hard to build anything meaningful. I want to work somewhere with a clear, consistent vision." },
      { employee_id: "EMP006", department: "Design", tenure_years: 2, primary_reason: "Better opportunity", response: "The new role is fully remote and in a field I'm more passionate about. Nothing wrong with the company — it's just the right time for me to move on." },
      { employee_id: "EMP007", department: "Sales", tenure_years: 6, primary_reason: "Compensation", response: "Six years and only two raises. The lack of financial recognition for top performers sends a message about how the company values us." },
      { employee_id: "EMP008", department: "Engineering", tenure_years: 1, primary_reason: "Culture fit", response: "The actual culture didn't match what was described during hiring. I was promised innovation but found bureaucracy and resistance to new ideas." },
      { employee_id: "EMP009", department: "Customer Success", tenure_years: 3, primary_reason: "Management issues", response: "Constant reorganizations and changing reporting structures created chaos. We had four different managers in three years. It's exhausting." },
      { employee_id: "EMP010", department: "Marketing", tenure_years: 7, primary_reason: "Retirement", response: "After 7 wonderful years, it's time to retire. I'm proud of what we built together. This company gave me some of my best professional years." },
    ],
  },

  mixed_feedback: {
    name: "Mixed Stakeholder Feedback",
    description: "10 stakeholder feedback responses from a mixed-methods study",
    data: [
      { respondent_id: "RSP001", stakeholder_type: "Community Member", region: "Urban", response: "The new policy has improved access to services dramatically. Wait times are down and staff are more helpful. Real positive change in our neighborhood." },
      { respondent_id: "RSP002", stakeholder_type: "Business Owner", region: "Rural", response: "Regulations are strangling small businesses. We can't compete with large corporations who can absorb compliance costs. It's driving us out of business." },
      { respondent_id: "RSP003", stakeholder_type: "NGO Representative", region: "Suburban", response: "Implementation was rushed without adequate community consultation. The underlying goals are right but the execution has created unnecessary friction." },
      { respondent_id: "RSP004", stakeholder_type: "Government Official", region: "Urban", response: "We've seen measurable improvements across all key performance indicators. The data clearly shows the program is working as intended." },
      { respondent_id: "RSP005", stakeholder_type: "Community Member", region: "Rural", response: "Nothing has changed for us in rural areas. All these improvements are happening in cities while we're left behind as always." },
      { respondent_id: "RSP006", stakeholder_type: "Academic Researcher", region: "Urban", response: "The evidence base for this intervention is mixed. Some outcomes show improvement while others show regression. More longitudinal data is needed." },
      { respondent_id: "RSP007", stakeholder_type: "Business Owner", region: "Urban", response: "The streamlined permitting process has saved us time and money. We were able to expand our operations because of these changes." },
      { respondent_id: "RSP008", stakeholder_type: "NGO Representative", region: "Rural", response: "Vulnerable populations are falling through the gaps. The system wasn't designed with their needs in mind and it shows in the outcomes data." },
      { respondent_id: "RSP009", stakeholder_type: "Community Member", region: "Suburban", response: "I appreciate the transparency in reporting. Knowing what's actually happening with public funds builds trust, even when results are mixed." },
      { respondent_id: "RSP010", stakeholder_type: "Academic Researcher", region: "Suburban", response: "This represents a significant policy innovation. The participatory design process was genuinely inclusive and the implementation reflects that." },
    ],
  },
};
